config/routes.rb
CocktailMaker::Application.routes.draw do

  resources :drinks, only: [:new, :create]
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  get "/drinks(.:format)" => "drinks#index"
  get "/drinks/:id(.:format)" => "drinks#show"

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  attr_accessible :name, :video_id

  validates :name, presence: true
  validates :video_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    render json: Drink.all

  end

  def new
    @drink = Drink.new
  end

  def create
    @drink = Drink.new(params[:drink])
    if @drink.save
      flash[:success] = "Drink Added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    render json: Drink.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def help

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/drinks/new.html.erb
<h1>Add Drink</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@drink) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :name, "Drink Name" %>
            <%= f.text_field :name %>

            <%= f.label :video_id, "Youtube ID" %>

            <%= f.text_field :video_id %>
            <div class="alert alert-info">
                Youtube ID is: <br>  <small>http://www.youtube.com/watch?v=</small><strong>this_bit</strong>
            </div>
            <input  type="submit"  value="    Add Drink     " class="button glow button-rounded button-flat-action"/>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Cocktail Maker by Michael Banfield
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",   '#' %></li>
            <li><%= link_to "Contact", '#' %></li>

        </ul>
    </nav>
</footer>

app/views/layouts/_github_banner.html.erb
<a href="https://github.com/mikeyb555/angular_muckaround"><img style="position: absolute; top: 0; z-index: 9999; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" alt="Fork me on GitHub"></a>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "cocktail maker", root_path, id: "logo" %>
            <nav>
                <ul class="nav pull-right">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Help", help_path %></li>
                    <li><%= link_to "Add Drink", new_drink_path %></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app = "CocktailMaker">
<head>
    <title>Cocktail Maker</title>
    <link href="//releases.flowplayer.org/5.4.0/skin/minimalist.css" rel="stylesheet">
    <%= stylesheet_link_tag    "application", media: "all" %>

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <% if Rails.env.development? %>
        <br>
        <strong>Build Status: </strong><img src="https://drone.io/github.com/mikeyb555/angular_muckaround/status.png" class="img-polaroid">
    <% end %>
    <%= debug(params) if Rails.env.development? %>

</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
<script src="//releases.flowplayer.org/5.4.0/flowplayer.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular-resource.min.js"></script>
<%= javascript_include_tag "application" %>
<%= render 'layouts/github_banner' %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/_order_list.html.erb
<div class="well">
    <ul class="nav nav-list">
        <div ng-model = "selection" ng-repeat="drink in drinks">
            <li><a tabindex="-1" href="#" ng-click = "showDrink(drink)">{{drink.name}}</a></li>
            <li class="divider"></li>
        </div>
    </ul>

</div>

app/views/static_pages/_select_show.html.erb
<div class="select-display" ng-show="selected">
    <label>Put your Bartender name in here (gimmick win!):</label>
    <input type="text" ng-model="yourName" placeholder="Enter a name here">
    <hr>
    <h1>Hello {{yourName}}!</h1>
    <h1>Drink Name: {{selectedDrink.name}}</h1>
    <div class="video-frame">
        <iframe width="560" height="315" src="//www.youtube.com/embed/{{selectedDrink.video_id}}" frameborder="0" allowfullscreen></iframe>

    </div>

</div>

app/views/static_pages/_video_show.html.erb
<div>

    <div>
        <%= render'welcome_page' %>
        <%= render 'select_show' %>
    </div>
</div>

app/views/static_pages/_welcome_page.html.erb
<div class = "welcome-page" ng-hide="selected">
    <div class="hero-unit">
        <h1>Welcome to Cocktail Maker!</h1>
    </div>
</div>

app/views/static_pages/help.html.erb
<h1>Help Page</h1>

app/views/static_pages/home.html.erb
<div class="row" ng-controller="ListCtrl">
    <div class="span4">
        <%= render 'order_list' %>
    </div>
    <div class="span8">
        <%= render'video_show' %>
    </div>
</div>